### ISSUE TITLE
1. As a component, I want to be able to read from and write to the Firestore database so that users can persist information.

### ISSUE THREAD

**Issue by fullybaked** [the-collab-lab/tcl-40-smart-shopping-list#1]
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.
AC:
*  [`firebase`](https://www.npmjs.com/package/firebase) has been added as a project dependency
* Making a change in the Firestore database will update the data in the app
* Making a change in the app will update the data in Firestore

Notes:
* Don't do too much here. In the past, pairs have built the whole add item form in the first week. The best approach is just to make a throw away view with a `<button/>` and a `<div/>`. Click the `<button/>` to send some data to the database. Have the data show up in the `<div/>`. Simple!
* If you need additional direction on how to use Firebase, you can read through the [Quickstart Guide](https://firebase.google.com/docs/firestore/quickstart) for understanding how to [add items to Firestore](https://firebase.google.com/docs/firestore/quickstart#add_data), as well as the Snapshot Guide for [creating a snapshot subscription](https://firebase.google.com/docs/firestore/query-data/listen#listen_to_multiple_documents_in_a_collection) to read and update data in real-time.

---

Quick Tips:
<details>
<summary>How to send data to Firestore</summary>

```javascript
      import { collection, addDoc } from 'firebase/firestore'
      try {
          const docRef = await addDoc(collection(db, COLLECTION_NAME), {
            property: 'value'
            // ...data
          })
          // Success!
          console.log(docRef.id)
      } catch (e) {
          // There was an error sending data to Firestore
          console.error(e)
      }
```

</details>

<details>
<summary>How to listen to data from Firestore</summary>

```javascript
      import { collection, onSnapshot } from 'firebase/firestore'
      const [docs, setDocs] = useState([])
      useEffect(() => {
          const unsubscribe = onSnapshot(collection(db, COLLECTION_NAME), (snapshot) => {
            // Firestore requires that you loop through the snapshot to access the docs,
            // instead of just setting the snapshot as the value of the state
            const snapshotDocs = []
            snapshot.forEach(doc => snapshotDocs.push(doc))
            setDocs(snapshotDocs)
          })
          return () => {
            // Used to remove the snapshot listener when the component is unmounted
            unsubscribe();
          }
      }, [])
```

</details>

**Comment by mxmason** [comment]
This was closed with the merge of #17, which continued on the work in #15
