### ISSUE TITLE
10. As an item, I want my estimated next purchase date to be computed at the time my purchase is recorded in the database so the app can learn how often I buy different items.

### ISSUE THREAD

**Issue by fullybaked** [the-collab-lab/tcl-40-smart-shopping-list#10]
AC:

* When a purchase is recorded, the estimated number of days until the next purchase date should be calculated and recorded in the database

The function `calculateEstimate` from `@the-collab-lab/shopping-list-utils` should be used to calculate the next estimated purchase interval. This should already be installed in your project from issue #3.

`calculateEstimate` accepts three arguments. They are, in order:
- `previousEstimate` (a number): The last estimated purchase interval
- `daysSinceLastTransaction` (a number): The number of days since the item was added to the list or last purchased
- `totalPurchases` (a number): The total number of purchases made for the item

Given this information, `calculateEstimate` returns **a whole number** indicating the number of days until the user is likely to buy this item again.

Notes:

* Think through the arguments that must be passed to `calculateEstimate` and how to use the information `calculateEstimate` returns.
* It is likely at this point you'll need to adjust the schema for an item to accommodate the data points required.

**Comment by lindseyindev** [comment]
If you're interested in seeing the [calculateEstimate function](https://github.com/the-collab-lab/shopping-list-utils/blob/main/src/calculateEstimate/index.ts) I've linked it! For this issue focus on the parameters the function takes and what the function returns and then use that value to add the prediction time to each item
