### ISSUE TITLE
Inputs aren't clickable until refreshing

### ISSUE THREAD

**Issue by k-schrattenholzer** [the-collab-lab/tcl-40-smart-shopping-list#24]
I think this has something to do with our inputs needing a value, and an on-change handler

**Comment by mxmason** [comment]
Would you mind adding reproduction steps, so that other developers can observe and possibly diagnose the bug? I couldn't get the app into this state on my own.

**Comment by k-schrattenholzer** [comment]
Yes! 
When I'm working on the code, and I make a change (in my editor) the inputs lock up and require a refresh to become clickable. But now that I'm trying to reproduce this, it seems like it might be a development specific bug because I can't reproduce it either.

**Comment by k-schrattenholzer** [comment]
Closing due to realizing this is a dev specific bug - possibly related to code changing in the editor, and the live server needing a re-render
