### ISSUE TITLE
When a checked item is un-checked on the list Firebase changes the lastPurchaseAt date to now

### ISSUE THREAD

**Issue by k-schrattenholzer** [the-collab-lab/tcl-40-smart-shopping-list#25]
I'm not entirely sure how to accomplish a fix - but when a user is un-checking an item, I think we want to update the lastPurchaseAt date to the date it was previous to the check & un-check (right? like if a user clicks an item and then decides to not purchase it, we shouldn't update firebase with the purchase date is my thought)

**Comment by mxmason** [comment]
My thinking: You cannot *un-purchase* something. If an item was purchased on May 2nd, un-checking it shouldn't revert that. I would think that checking an item should create a new purchase date, and unchecking should have no effect on the date.

**Comment by k-schrattenholzer** [comment]
I see what you're saying - the case I'm thinking of is, 

- I'm at the grocery store, and I put grapes in my cart.
- I check them off my list, and the last purchased date is updated to now
- BUT I realize I just bought grapes or don't need them, and take them out of my cart & do not purchase them

In this case wouldn't we want to revert the last purchasedAt time to when I bought them previously? Or if i'd never bought them, wouldn't we want to bring that value back to null?

**Comment by mxmason** [comment]
That's a great point. I think we should keep this enhancement in mind for future work. We should also keep in mind that there are two ways a checkbox can become un-checked:
1. upon user interaction, and
2. when an item becomes 'stale' and we uncheck it for the user

We only want to revert to the previous `lastPurchasedAt` in the first case.

**Comment by k-schrattenholzer** [comment]
Closing - it looks like one of our recent PR's adressed this issue. Now, only the isActive is modified when an item is unChecked
