### ISSUE TITLE
Update LocalStorage to 

### ISSUE THREAD

**Issue by k-schrattenholzer** [the-collab-lab/tcl-40-smart-shopping-list#33]
Currently, localStorage is storing our token as a string. But to give the user the ability to track the lists they've joined previously, we want to have this token stored in an Array so we can access the other tokens 

AC: 
- next to the join list input, a dropdown should be visible with all previously input tokens for the user to select (with submit)
- stop auto re-routing to list view once a token is added to local storage

**Comment by lindseyindev** [comment]
This is a great idea and a cool way to accomplish it! Excited to see the implementation
