### ISSUE TITLE
Styling AddItem Form

### ISSUE THREAD

**Issue by k-schrattenholzer** [the-collab-lab/tcl-40-smart-shopping-list#37]
The AddItem form should be user friendly, and visually pleasant.
This is a bit open-ended in terms of the form styling, but we did note that the error/item-added message should appear more visually differentiated from the form and inputs (currently it's in-line with the item name input).

**Comment by lindseyindev** [comment]
Some examples of the radio button outline styling I found if this is helpful

https://stackoverflow.com/questions/10849626/putting-css-borders-around-radio-buttons

https://stackoverflow.com/questions/43589287/change-border-color-of-radio-button-when-selected --> [with this example](https://stackoverflow.com/questions/43589287/change-border-color-of-radio-button-when-selected)
